### ISSUE TITLE
Mounting paths for kubernetes

### ISSUE THREAD

**Issue by dzegarra** [CatoTH/antragsgruen#768]
I'm using the docker image from [jugendpresse](https://github.com/jugendpresse/docker-antragsgruen) to deploy this application in a Kubernetes cluster. I plan to make some changes to jugendpresse's Dockerfile to run composer and npm during the creation of the image instead of during the initialization of the container. But, for that to work, I need to know which directories of the application I should mount externally I could make available to the new container instead the previous crashes or share it with other replicas of the same container. 

Could you confirm for me if these two paths are the only ones that users can change?

```yaml
volumeMounts:
  - name: assets
    mountPath: /var/www/html/web/assets
  - name: runtime
    mountPath: /var/www/html/runtime
```
